### ISSUE TITLE
Introducing Scrum

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#1]
Please document what different scrum questions and varieties exist and note down the translation into your mother tongue here.

**Comment by championswimmer** [comment]
I do not have a lot of experience with Scrum, the only place I interned, had a daily standup where we answered the following questions : 

1. What did you work on today ? 
2. What roadblocks you faced if any ? Would you like your teammates to help in any of them ?
3. How much of your initial target for the day you could finish ?
4. What do you plan to do tomorrow ? 

P.S. English is my first language. So no translation needed for me.

**Comment by mariobehling** [comment]
Thanks! Good input. @rafalkowalski How about you?

**Comment by leto** [comment]
I have been using scrum in the industry for about 8 years. It boils down to answer 3 questions: 

1) What have you done yesterday (since the last update)? 
2) What are you working on today (or until next update) ? 
3) What is blocking or preventing you from working? i.e. what do you need help with?

There is no time estimating involved, which is a different activity.

Please let me know how I can help explain how it works or why it is such a good idea. My suggestion is that each student answer the 3 questions above in text form and notify Mario and I, at least weekly and preferably each work day. @mariobehling do you have a preference for those updates to be in IRC/email/wiki/etc ? I think all students being able to see each others updates is essential and the more public the better. Whichever gets out of the way and let's us accomplish as much as possible is the best solution for us.

**Comment by rafalkowalski** [comment]
I use scrum every day, we daily discuss about  "What I have done yesterday", "What I'm going to do today", "What are the obstacles?", "Do I need help from someone?", and weekly "what I've done over the week?" , "What enjoyed me at?" and "Summary of the work of the whole team".

**Comment by mananwason** [comment]
I also used scrum when I interned earlier. They gave me a window of 2 days. Every alternate day, I had to give them information about I had done in the last 2 days with screenshots of my work and what do I have to do in the next 2 days with a brief explanation. 
I also mentioned any issues I faced during this period and what did I do to solve them.

**Comment by mananwason** [comment]
@mariobehling @leto We should get a common consensus on the format of the scrum, so that we can get started by tomorrow.

**Comment by mariobehling** [comment]
Please use the three scrum questions. We can always redefine later. The important thing is, let's get started.

**Comment by mananwason** [comment]
Sure :smiley:
