### ISSUE TITLE
Existing samples non-functional

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event#138]
The current samples are not functional. After creating an APK from the app generator, it shows the following when I try to install and run the application. 

![screenshot_20170513-094310](https://cloud.githubusercontent.com/assets/21010060/26022468/c47bd2d6-37c3-11e7-83bc-c666730004fc.png)

@mariobehling @niranjan94 Can I work on it?

**Comment by niranjan94** [comment]
@mahikaw 
- first ensure if the problem lies in the sample or the generator.
- Test other samples with generator
- Check the generator codebase to see where and how the API endpoint information is obtained and added to the app
- Then see if the location from where the generator tries to get the endpoint is the same as the location where it is actually stored in the sample.

**Comment by mahikaw** [comment]
sure, thanks for these steps @niranjan94 I am on the 3rd step, the current samples are not working.

**Comment by mahikaw** [comment]
Has been resolved in one of the commits.
