### ISSUE TITLE
How can we have the app in different languages?

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#14]
How can we work with translators? Where is the best place to work on xml translations? What options do we have?

**Comment by mananwason** [comment]
@mariobehling We need to create different String resources for in app values and for data we can use string locale but It's not advisable. Best Thing would be to maintain separate sheets and we can very easily translate each cell in the sheets as well using =GoogleTranslate("text", "source language","target language")

**Comment by creativepsyco** [comment]
Transifex is one tool that can help. Its free for open source projects and other people can help you translate application specific strings. For data translations, you will definitely need to maintain different JSON files which can be retrieved using a specific parameter in the HTTP query string. https://www.transifex.com/

**Comment by rafalkowalski** [comment]
Maybe it is good idea https://code.google.com/p/google-api-translate-java/?

**Comment by championswimmer** [comment]
My experience with crowdin has been very good. Because somehow for single
words or small phrases, Google translate doesn't do a good job.

Given we can get some friends, fossasia members (who are from different
languages...  And maybe this way also get the larger community involved)
etc to help us out, crowdin will really good.
