### ISSUE TITLE
Lack of clarity in planning for the app

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event#15]
I believe that a clear plan of features has not been put up anywhere. So I suggest we make a plan on the features we want in the final app and add them in the respective repo as tasks. This will allow us to take up those tasks and complete them in an orderly manner, thus increasing efficiency.
Please give your inputs on this. @mariobehling @leto @rafalkowalski @championswimmer

**Comment by championswimmer** [comment]
Yes that's right. I was hence making only the data related parts, and had
not started with the GUI side as we need consensus on that.

One basic requirement we need to keep in mind is, any data, color, logo
related to the event should not be hardcoded or hard to swap during run or
build.

**Comment by mananwason** [comment]
I agree @championswimmer but Shouldn't we have a structure on how the server will hold the info and how it would provide it to json format to work on data related parts as well.

**Comment by mariobehling** [comment]
Hi, please let's keep the language here positive. Instead of "lack of clarity" I would have preferred to see an issue here from you "Put together a Feature List for all components" or something similar. Please understand, that this is part of your project to propose features and list them. For the beginning the idea is, that you work with the existing app and learn about the requirements.

Now, the next step is to make a feature list and plan. 
1. Please add your ideas here https://github.com/fossasia/open-event/blob/master/FEATURE.md
2. Please discuss questions here https://github.com/fossasia/open-event/issues/16

**Comment by mananwason** [comment]
Hi Sorry for the negativity. I didn't quite realise it. I understand that proposing and listing the features is  part of our project. I just wanted to get the process started by listing it as an issue and collaborating with everyone to get the best list of features for the apps.
I would like to suggest that instead of maintaining a file on github, we should use gdocs and put the final list of features on github after a careful set of additions and deletions to get the perfect list.

**Comment by mariobehling** [comment]
Hi Manan, let's not make it complicated. We can change an md at any time and it is easy to reference stuff within Github. I do not see the need for another thing yet. How about we start to list some features first and if we need another service, we can do so at any time.

**Comment by mananwason** [comment]
Sure Mario, I'll get right on it.

**Comment by championswimmer** [comment]
@mananwason
The structure for how server will hold data and how the JSON api will work
is infact already decided and a bit of preliminary work has been done.
There's much left, but we have some pointers to follow for the time being.
General discussion about planning of the project was taking place here
https://gitter.im/fossasia/open-event

And the corresponding repo
https://github.com/fossasia/open-event
contains documentation for 1) database model in DATABSE.md, 2) json API, in
API.md for now.
Like Mario said, lets put up app features also there. Since we are making
it a open github project, it's best we also document out plannning out
there only :)

**Comment by mananwason** [comment]
Sure @championswimmer, I have seen the repos you mentioned, but I am not sure how to enter data and retrieve it. This is just the database I presume.

**Comment by leto** [comment]
@mananwason create an issue for each task and please assign them each to a milestone: https://github.com/fossasia/open-event/milestones When reporting scrum updates, reference which milestones you are working and how close they are to completion

**Comment by championswimmer** [comment]
There are 2 ways, down the repo, run install.sh to get the deps, and then
$ python run.py

to set it up locally.

Or, to make things easy for all of us, I am hosting it on my website too
http://springboard.championswimmer.in:8080/admin/

One slight caveat, on my server, it might not be latest always. I manually
pull the changes from github. So if anyone else makes some changes to
github, it isn't reflected immediately on the app hosted on my website,
untill I get online next time. I will take some time out to implement a
github webhook so it always stays updated.

You can use app on my server to create db entries, and get json results.

**Comment by championswimmer** [comment]
P.S. The api endpoints look like this

http://springboard.championswimmer.in:8080/get/api/v1/sessions

**Comment by mananwason** [comment]
This is good work !! What platform did you all use to build this?

**Comment by rafalkowalski** [comment]
Flask mini-framework

http://flask.pocoo.org/

**Comment by leto** [comment]
@championswimmer awesome work! Is the code that runs that committed and pushed?

**Comment by championswimmer** [comment]
I try to keep it always updated. But it isn't auto-updated right now. I
manually pull.
I'll make it auto. Should not take me more than an hour at max. I have make
github webhooks before :)
