### ISSUE TITLE
changing format of susan chen picture

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event#180]
The current format of the photo is jpeg which should be jpg instead. sending a pr for the fix.

**Comment by niranjan94** [comment]
@arp95 both jpg and jpeg are the same format and just the extension varies. And both are valid too. Why is this as issue?

**Comment by Princu7** [comment]
@niranjan94 Yes. Both are valid. The problem is that in the speaker JSON file, the image is specified as `susan_chen.jpeg` while in the images folder, it exists as `susan_chen.jpg`. So, when we generate the app through the API, the file doesn't get downloaded since no such file as that given in the JSON (`susan_chen.jpeg`) exists. This would not have been an issue if extensions (no matter jpeg, jpg or png) were consistent in both the places (file and the images folder). Hope this is correct. Thanks :)

**Comment by niranjan94** [comment]
Cool. Thanks for the explanation @Princu7... @arp95 always give a proper issue description.

**Comment by arp95** [comment]
@niranjan94 will take care from next time. sorry for it.
i know they are of same format but @Princu7  was facing issues as he told.
