### ISSUE TITLE
Feature List and Project Plan for Android App (2015)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event#23]
Please define the following for your project
a) Feature List (add it to Feature.md)
b) Project Plan with possible milestones (Which features will be implemented at what time)
c) Technologies used

Proposed Milestones
* Milestone 1, Due by June 10, 2015
* Milestone 2, Due by June 26, 2015
* Milestone 3, Due by July 25, 2015
* Milestone 4, Due by August 21, 2015 

> Project 3 (Manan): Android App (newly developed) -- https://github.com/fossasia/open-event-android
Also refer to https://github.com/fossasia/open-event/issues/19

**Comment by mananwason** [comment]
Milestone 1 :
* Basic structure for the app with navigation drawer and fragments
* Data retrieval from orga server using volley 
* Version checking to see if the freshness of data in database
* SQLite Database with all data retrieved from server being stored after version checking
* Data retrieved from the database and displayed in respective locations.
*  Alphabet indexing for speakers
* Map Fragment inserted 
* Collaborate with other to sync up the projects

Milestone 2 :
* BookMarks fragment fully operational
* Add changing themes from data retrieved via server
* Make custom about dialogs and change their info on changing data
*  Work on Bugs and try to fix them
* Improve UI and make it more user friendly
* Making sharing of event data happen
* Complete Updation of database

Milestone 3 :
* Make Notifications for upcoming events work
* Add Search functionality
* Start working on a wearable app
* Make it possible to share data through NFC, android beam
* Fix bugs
* Add social media compatibility ( Not yet decide what to use for this)
* Add Google calendar Functionality

Milestone 4:
* Work on appearance of the app, finalise the UI and add recycler view and cardview wherever possible instead of lists to make it efficient
* Start refactoring to make things more efficient
* Make Notifications work on android wear
* Finish the wear app.
* Fix Bugs 
* Test the app
* Create another branch for f-droid.
* Publish on play store and f -droid.
* Collaborate with others to discuss additional functionality.

**Comment by leto** [comment]
"Fix bugs" and "Work on bugs" are not valid milestone bullet points.

**Comment by leto** [comment]
Also "test the app" is not sufficiently descriptive. You will be testing it at every stage. What kinds of tests will you write at each stage? Which test suite and test framework? In general, all of your Github issues/questions/comments/emails have been lacking detail, requiring us to pry it out of you. Please add more detail, MUCH MORE DETAIL, in all your future correspondence. This will directly effect your mid-term grade.

**Comment by mananwason** [comment]
Hi @leto Yes I would be writing tests at every stage. I am not sure what tests yet. But I am mostly certain that I'll be using junit testing for this. I am sorry about less details in the past, but I have started giving out details on what I did, and what I didn't and why I didn't do it etc. in my scrum and questions. I have been giving links as well now. Please tell me if it still lacks some kind of detail, I'll improve it in my future correspondence. Thanks.

**Comment by creativepsyco** [comment]
@mananwason Take a look here: https://github.com/fossasia/open-event-android/issues/6, Testing can be done using Espresso which facilitates writing of UI Tests. You can write unit tests for complicated pieces of code but don't write tests for simple DB related calls. The tests should carry a good purpose at the end of the day and help you catch mistakes in your code or whenever you update the code base with a Pull Request.

Also, I would recommend that committing and pushing to the master branch should be avoided at all costs. Please create a Pull Request. See [PR Tutorial][1] and assign some one else who can take a look at the code and point out any issues with it.  

I have some questions:
* Are you still going with Volley for your Network Implementation? `OkHttp` + `Retrofit` are a much cleaner implementation
* I don't quite agree with cardview making things more efficient, Its just a UI thing 
* Make it possible to share data through NFC, android beam - I would keep this low priority because there's not enough market for these features
* Start refactoring to make things more efficient - Refactoring is a continuous process, don't need a milestone for that.
* Collaborate with other to sync up the projects - what does this mean? 

Agree with @leto on a lack of detail but as long as the features/issues are listed out and milestone applied, we can discuss on timeline etc. while you start with implementation.

[1]: http://yangsu.github.io/pull-request-tutorial/

**Comment by mananwason** [comment]
@creativepsyco I'll look into expresso
Me and @championswimmer had discussed on what to use for networking and we decided to use volley only right now and afterwards create a branch with retrofit+okhttp afterwards but I think now that I should use the latter only first, then see about volley afterwards. This will help us try something new as Volley is already being used in the previous apps. Also I am going to use picasso for images.

**Comment by creativepsyco** [comment]
I can put a template for OkHttp + Retrofit in a branch if you want.

**Comment by mananwason** [comment]
Please go ahead but in what ever I have researched I didn't see okhttp with retrofit used anywhere for jsonparsing and caching. This seems to be the best combo for REST based communication only. The best model I found for the work we need to do is using Volley hooked with okHttpStack.

**Comment by mariobehling** [comment]
@creativepsyco Yes, please add a template for OkHttp + Retrofit in a branch. We count on your experience here and it sounds like the most suitable solution.

**Comment by mananwason** [comment]
@mariobehling @leto @creativepsyco I have added maps to Milestone 2 due to the license issue.
https://github.com/fossasia/open-event-android/pull/27

**Comment by championswimmer** [comment]
Closing this, as this was for GSOC 2015. We need to create new roadmap for 2016 and future
